### ISSUE TITLE
Can't upload model files through git-lfs

### ISSUE THREAD

**Issue by helloahn** [nnsuite/testcases#4]
when I try to push large files with `gst-lfs`, I confront with below error.

```bash
batch response: Post https://github.com/nnsuite/testcases.git/info/lfs/objects/batch: proxyconnect tcp: tls: oversized record received with length 20527
error: failed to push some refs to 'https://github.com/nnsuite/testcases.git'
```
can I have a solution?

**Comment by myungjoo** [comment]
We cannot use LFS with nnsuite github. It is a paid service and I didn't pay github. :)

**Comment by helloahn** [comment]
ok then, I will upload the model files without lfs.

**Comment by leemgs** [comment]
[FYI] https://github.com/nnsuite/TAOS-CI/blob/master/ci/doc/how-to-archive-large-data.md

**Comment by myungjoo** [comment]
@helloahn @leemgs 

Because we now have AWS machines running, we may upload a few large NN model files to AWS instead of LFS. (Discretion advised anyway... it's not free.)
